version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_lb
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL:-blue}
    ports:
      - "8080:80"
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_network
    restart: unless-stopped

      
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - APP_COLOR=blue
      - APP_POOL=blue
      - PORT=${BLUE_PORT:-3000}
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "${BLUE_PORT:-8081}:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/healthz"]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - app_network

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - APP_POOL=green
      - APP_COLOR=green
      - PORT=${GREEN_PORT:-3000}
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "${GREEN_PORT:-8082}:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/healthz"]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - app_network


networks:
  app_network:
    driver: bridge